name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false


      - name: Build
        run: |
          sudo git submodule update --init --recursive --remote   
          sudo npm install
          sudo npm install hexo-cli -g 
          sudo hexo clean
          sudo hexo d

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./public
